travis:
  secure:
    BINSTAR_TOKEN: dNMYhMOWuHbrL6DW1ln7Vs6PvG3Vcj4sXs+5wK+blk/ghw8ooVbAdhMA3sFCp7Tpky9jyxtqvhVXNj6O/KTWPpZe9eIpSyhWIWDhumHAJAOmrdwDqiTuCwRyiguodCm072GoahymshKSxxH4dfg9lgKuKpRkbY9x49S9X3ZOdHdzdbNSd2nFRvKFBDo69nFnRT4NIZK8Mv36qKYWpKTDcU10WH1cNTchwHia7yg+pJCR0bGYE48bMIgzB1AynIvJw72e0HLPS+6uSfBeUQRhuBJB0184iBmmY/WdOsnjZhcNt4Xq4sTbbcEbPAkxGo10vXZxJhhj4uEkTlKsFhsMpHen736VE/HTSHna4/ngwLoGG8nDm0sW01K34WK0D8X0FdjC+StBGgLrIbCgtRqgZANL9avT+xR9QofKABEFrelGeIDsB6RSLtjraXKeIVCuY2Okv3OjMopDJTz+/GCgrBNFAJ2WdoPLYeiybK5jbnxKLlOPU5+59DVNFTMRejh/G0G4rZq1lzHsR9g0eEyWG0P2uy+ryOYTb1H7LeeLyaKz4IPhRkPBIDQy9lDneH9Q6+ddaS2wnaRpbCQAePWCeX/r8W2g1cAtWithz7Q3ejtXgFvwf5Pax7jT4BZHEy8B4Bv6MgjWWTSUGUxHV882ABagmL4PgOLvl+LUtXCUWRY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
